/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, Html } from '@react-three/drei'

const name = (props) => {
  return (
    <span className="stand-name">
      {props.name}
    </span>
  )
}

const infoDisplay = (props) => {
  if (props.displayType === "READY") {
    return (<>
      <p
        className="stand-ready-status"
        style={props.ready? {color: "limegreen"} : {color: "red"}}
      >
        {props.ready? "READY" : "UNREADY"}
      </p>
    </>)
  } else {
    console.log(props.displayType)
  }
}

export default function Model(props) {
  const group = useRef()
  const { nodes } = useGLTF('/stand.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
      >
        <Html
          distanceFactor={1.5}
          position={[0, 1.7, 1]}
          transform>
            {name(props)}
            {infoDisplay(props)}
        </Html>
      </mesh>
    </group>
  )
}

useGLTF.preload('/stand.glb')